# Generated by Django 4.1.5 on 2023-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketbasket',
            options={},
        ),
        migrations.AlterField(
            model_name='marketbasket',
            name='Date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketbasket',
            name='Member_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketbasket',
            name='itemDescription',
            field=models.CharField(default='', max_length=50),
        ),
    ]
